# Setup
title:               Naman Dwivedi
tagline:             naman14
url:                 https://blog.namand.in
paginate:            5
avatar:              https://namand.in/images/naman.jpg
twitter_username:    naman1405

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Naman Dwivedi
  url:               https://github.com/naman14
  email:             namandwivedi14@gmail.com
  tagline:           naman14

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/naman14/naman14.github.io

# This is the list of pages to incldue in the header of the website.